### ISSUE TITLE
Ramping artifact on flight 02/09/2023

### ISSUE THREAD

**Issue by brentwilder** [SnowEx/ice-road-copters#10]
There is an issue with flight 02/09/2023. Spatial patterns don’t make sense compared to the rest of the flights. A clear gradient is visible from top to bottom of the image (parallel with the road). Image courtesy of @Surfix .

![Screenshot 2024-01-12 at 16 27 15](https://github.com/SnowEx/ice-road-copters/assets/56372982/74e5e9ae-9b6d-4eba-b178-1572f062ad0e)

So this appears to be a co-registration issue. I tested Ames Stereo Pipeline's pc_align tool running two options on the roadway used as GCP,
- Option#1 translational + rotational
- Option#2 just translational 

Option#1 is shown in Naheem's figure and has ramping effect top-left to bottom-right. After running Option#2, I found ramping occurring from top-right to bottom-left, but performed even worse. Roadway difference which should ideally be 0 +/- 10cm based on our other flights, was 20 +/- 35 cm using Option#2. 

![issue](https://github.com/SnowEx/ice-road-copters/assets/56372982/ea68e6b6-95e4-4956-8062-6051a7467755)

I was curious to see if other flights exhibited this gradient pattern on the roadway so I tested the 12/08/2022 flight. I did not find such pattern and it looked like normal noise (mixed with reds and blues). Which is good.

So what is going on with the points over the roadway for this flight? There is a clear ramping signal on the roadway that is then being superimposed onto the rest of the dataset...I would love to hear all of your thoughts on this.

@ZachHoppinen @shadoneel  @Surfix

**Comment by brentwilder** [comment]
## Hey all, I believe I've found the root cause of this issue.

We currently use a buffer of 2.5m on either side (5 m wide) of the road shpfile. I took great care in getting as close to the centerline when drawing this last year, however, I did not account for the width of the road decreasing due to large snowbanks along the roadway. As you can see in the diagram here, the shape cuts into the snowbank for quite a ways (this stretch is about 300 m).  With snowbanks being quite tall, this would be enough to drive the ICP algorithm to create the ramping seen in the figure above.

![Screenshot 2024-01-13 at 14 46 57](https://github.com/SnowEx/ice-road-copters/assets/56372982/14e57dda-9be2-461a-895a-43de8ebcabf2)


## Here is another example showing a turnout in the snow-free DEM, that was then used as a snowbank in the snow-on DEM
![Screenshot 2024-01-13 at 15 15 15](https://github.com/SnowEx/ice-road-copters/assets/56372982/1ff5aaf6-0431-45f9-9297-f905a611604c)
![Screenshot 2024-01-13 at 15 15 34](https://github.com/SnowEx/ice-road-copters/assets/56372982/a9a93ca0-4213-4b9f-810f-f5edc5cc5ac0)


## I think the best solution here for @Surfix and myself to salvage this flight for our papers would be to rerun with a smaller buffer area (for example 1m as shown below). I will also go ahead and upload a version 4 shapefile that will seek to improve the position with the road centerline.


![Screenshot 2024-01-13 at 15 01 28](https://github.com/SnowEx/ice-road-copters/assets/56372982/b44304db-f5bd-4f9c-a964-67572f45890a)


Additionally (on a slightly related note) our algorithm assumes the initial guess of the heli-lidar is "close enough". And by that I mean we are really just doing fine-scale adjustments at this time. If the unaligned DEM is off by a few meters in the X-Y, that would be enough to cause a bad fit as well. We could address this in the future if needed by performing a rough adjustment first based on the hillshade using ASP pc_align function (see docs here on --initial-transform-from-hillshading, https://stereopipeline.readthedocs.io/en/latest/tools/pc_align.html).  I don't believe we have had this issue yet because how are total translational vector has been under 3m and is almost entirely in the Z direction. But just something to consider.

**Comment by brentwilder** [comment]
I have just uploaded a version 4 of the road shape file that better fits the centerline by adding in about twice as many vertices as before. 

While re-drawing the road I saw many narrow sections caused by the snow banks. And often times the snowbanks encroach farther on one side more than another, which adds difficulty. 

Below is a diagram for a range of values we could select from and update the code. For reference, we are currently using 2.5m. My vote would be switching it to be 1m or 1.5m. This should improve co-registration performance. 


![Screenshot 2024-01-13 at 16 00 28](https://github.com/SnowEx/ice-road-copters/assets/56372982/3d09956c-414e-430c-98e3-5164d55d6285)

**Comment by shadoneel** [comment]
Nice work! Thanks Brent!  Sent from my iPhoneOn Jan 13, 2024, at 5:06 PM, Brent Wilder ***@***.***> wrote:﻿
I have just uploaded a version 4 of the road shape file that better fits the centerline by adding in about twice as many vertices as before.
While re-drawing the road I saw many narrow sections caused by the snow banks. And often times the snowbanks encroach farther on one side more than another, which adds difficulty.
Below is a diagram for a range of values we could select from and update the code. For reference, we are currently using 2.5m. My vote would be switching it to be 1m or 1.5m. This should improve co-registration performance.
Screenshot.2024-01-13.at.16.00.28.png (view on web)

**Comment by brentwilder** [comment]
Thanks Shad.

Just to have this in writing, here is summary from emails.

#### We have decided on using 1.5m from centerline option (and calling it a 3m buffer). Testing coming soon..

**Comment by brentwilder** [comment]
@shadoneel @Surfix @ZachHoppinen 

I tested today with the two updates, and unfortunately  I didn't see significant improvement in the snow depth distribution. Still has the ramped effect.

I'm really at a loss... Here is an  image below shows a drift in error.. but this could be also caused by rotational error in the original lidar. I have run out of ideas to try here.

![image](https://github.com/SnowEx/ice-road-copters/assets/56372982/fe80e56c-69d0-46cc-876a-4c4f54c69879)


## Please if anyone has any thoughts on what could be causing the drift / ideas for other things to check

**Comment by brentwilder** [comment]
Was found to be a Riegl processing bug! Marking this as resolved!
